### ISSUE TITLE
changes to NppFavorites files doesn't affect display of favorites

### ISSUE THREAD

**Issue by dleigh** [heldersepu/nppfavorites#13]
Just started using this plugin today.  Not sure if it's still maintained.  When I edit the favorites file and save it, the changes are not reflected in the Plugins>NppFavorites dropdown menu display.  If I click on the right entry location the correct file is opened, but the display doesn't change for me.  Also, as I've seen others say, more than 6 entries would be great and a button to get to the favorites list as well.

Thanks for the work put into this plugin!

**Comment by ThioJoe** [comment]
Old thread so i'm sure you figured this out by now, but closing and re-opening Notepad++ makes it update the favorites list displayed

**Comment by dleigh** [comment]
Thank you!
