### ISSUE TITLE
Binaries not working in Windows 7

### ISSUE THREAD

**Issue by dougbreaux** [heldersepu/nppfavorites#4]
Both DLLs produce the error:

"C:\Program Files (x86)\Notepad++\plugins\NppFavorites.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support."

Then:

"%1 is not a valid Win32 application. This plugin is not compatible with current version of Notepad++. Do you want to remove this plugin from plugins directory to prevent this message from the next launch time?"

**Comment by AlbinoDrought** [comment]
Works over here on 64-bit Windows 10, compiled under "Unicode-Realeas"

**Comment by dougbreaux** [comment]
I downloaded the binaries, didn't compile myself.

**Comment by AlbinoDrought** [comment]
@dougbreaux I've made a fork and uploaded binaries compiled from my machine: https://github.com/AlbinoDrought/nppfavorites/releases/tag/4126e30

I am currently using the one from Unicode_Release and it is working great here, may be worth a shot.

**Comment by heldersepu** [comment]
I just recompiled the binaries, the should be working fine now.

**Comment by dougbreaux** [comment]
Hmmm... I don't see any new binaries here.

**Comment by dougbreaux** [comment]
I see them updated here now, thanks! Was I missing some other location for them? (And NppFavorites.dll is working for me.)
