### ISSUE TITLE
Why this plugin is not being shown in Plugin Manager?

### ISSUE THREAD

**Issue by tazotodua** [heldersepu/nppfavorites#6]
It will be nice if you add this plugin in repository (or whatever called), 
so we can install that directly from NPP>plugin manager

**Comment by chcg** [comment]
@heldersepu Using this plugin in plugin manager requires a release as a zip file. Additionally version information in the fileinfos is necessary. It seems to be part of https://github.com/heldersepu/nppfavorites/blob/master/version_info.rc, but not your current binary.

**Comment by heldersepu** [comment]
Sorry I never been too serious about this Plugin, it was just a little experiment for me...
There must be better alternatives out there

**Comment by chcg** [comment]
At least it is referenced in some community threads, see e.g.
https://notepad-plus-plus.org/community/topic/11619/feature-request-list-of-frequently-used-files/6

**Comment by heldersepu** [comment]
Wow...
It is more popular than what I expected...

I have no idea how to list it in Plugin Manager.

**Comment by chcg** [comment]
I already added a dummy entry at https://npppm.bruderste.in/plugins/view/nppfavorites. Just need a zip with version info to allow a download. For a x64 version: https://github.com/bruderstein/npp-plugins-x64

**Comment by heldersepu** [comment]
@chcg seems you have some experience with that... do you want to send a PR?

**Comment by heldersepu** [comment]
Sure sounds good to me! 
let's update to v3.1 and drop ansi support

**Comment by heldersepu** [comment]
here are the logs from AppVeyor:

```
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:37.70
cd "%APPVEYOR_BUILD_FOLDER%"
if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
   Push-AppveyorArtifact "bin64\NppFavorites.dll" -FileName NppFavorites.dll
}
if ($env:PLATFORM_INPUT -eq "x86" -and $env:CONFIGURATION -eq "Release") {
    Push-AppveyorArtifact "bin\NppFavorites.dll" -FileName NppFavorites.dll
}
if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORM_INPUTTOOLSET -eq "v140_xp") {
    if($env:PLATFORM_INPUT -eq "x64"){
        $ZipFileName = "NppFavorites_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
        7z a $ZipFileName .\bin64\NppFavorites.dll
    }
    if($env:PLATFORM_INPUT -eq "x86"){
        $ZipFileName = "NppFavorites_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
        7z a $ZipFileName .\bin\NppFavorites.dll
    }
}
Uploading artifact NppFavorites.dll (92,160 bytes)...100%
Discovering tests...OK
Collecting artifacts...
No artifacts found matching 'NppFavorites_*.zip' path
Deploying using GitHub provider
Creating "1.0.0.1.10" release for repository "heldersepu/nppfavorites" tag "1.0.0.1.10" commit "e5b0f72d1e63dfd2e56b84fc91220fdae4478468"...Skipped - release with tag "1.0.0.1.10" already exists
No artifacts were published. Make sure you have specified correct artifacts filter.
Updating "1.0.0.1.10" release for repository "heldersepu/nppfavorites" tag "1.0.0.1.10" commit "e5b0f72d1e63dfd2e56b84fc91220fdae4478468"...OK
Build success

```

**Comment by heldersepu** [comment]
I made some changes to the after script but still no dice:
**No artifacts found matching 'NppFavorites_*.zip' path**

```
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:05.59
cd "%APPVEYOR_BUILD_FOLDER%"
if ($env:CONFIGURATION -eq "Release") {
  Push-AppveyorArtifact "bin$($env:PLATFORM_INPUT)\NppFavorites.dll" -FileName NppFavorites.dll          
  if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:PLATFORM_INPUTTOOLSET -eq "v140_xp") {
    $ZipFileName = "NppFavorites_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:PLATFORM_INPUT).zip"
    7z a $ZipFileName ".\bin$($env:PLATFORM_INPUT)\NppFavorites.dll"
  }
}
Uploading artifact NppFavorites.dll (92,160 bytes)...100%
Discovering tests...OK
Collecting artifacts...
No artifacts found matching 'NppFavorites_*.zip' path
Deploying using GitHub provider
```

**Comment by heldersepu** [comment]
@chcg AppVeyor is finally doing what it is supposed to:
https://github.com/heldersepu/nppfavorites/releases/tag/1.0.0.1.21

I made a few changes, please double check when you can.
Does this closes this issue?

**Comment by chcg** [comment]
Look fine. Added the version to PM already and it available from the devlist until taken also for the normal list ~ next week. For x64 see https://github.com/bruderstein/npp-plugins-x64/commit/e2d2d0089b88714da4c007ab82aa22914f5508a0

PM just supports version numbers with 3 dots, so 1.0.0.1.21 is just listed as 1.0.0.1. So it would be good to use shorter versions for the next release. See e.g. semantic versioning at https://semver.org/.

Thanks for correcting\finalizing the appveyor config. 

So I think this issue could be closed now.

**Comment by heldersepu** [comment]
Perfect!
The last number was me to keep inline with AppVeyor but can definitely be ignored
